# Translation / inference options
model: models/keyphrase/meng17/kp20k.one2one.birnn.test_step_100000.pt

# Data options
data_type: keyphrase
src: data/keyphrase/meng17/kp20k_small/kp20k_small_test.src
tgt: data/keyphrase/meng17/kp20k_small/kp20k_small_test.tgt
shard_size: 0
output: output/pred/kp20k/kp20k.one2one_step_100000.pred

# Evaluation options
report_bleu: 'false'
report_rouge: 'false'
report_kpeval: 'true'
report_time: 'true'

# Options most relevant to summarization.
#dynamic_dict: 'true'
share_vocab: 'true'

# Beam search
beam_size: 32
#beam_size: 200
min_length: 1
max_length: 6

# Alpha and Beta values for Google Length + Coverage penalty
stepwise_penalty: 'false'

# Logging
verbose: 'true'
log_file: output/pred/kp20k/kp20k.one2one_step_100000.pred.log
log_file_level: 'DEBUG'
n_best: 100

# Efficiency
batch_size: 10
gpu: -1

tgt_type: multiple